services:
  coredns:
    container_name: coredns
    image: coredns/coredns:1.9.4
    ports:
      - 53:53/udp
      - 53:53/tcp
    volumes:
      - ./:/root/
    command:
      - -conf
      - /root/Corefile
    restart: always
