apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  type: NodePort
  selector:
    app: gateway
  ports:
    - port: 80
      nodePort: 31010
---
apiVersion: v1
kind: Service
metadata:
  name: orchestrator-api
spec:
  type: ClusterIP
  selector:
    name: orchestrator-api
  ports:
    - port: 80
      targetPort: 80
      name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestrator-api
spec:
  selector:
    matchLabels:
      name: orchestrator-api
  template:
    metadata:
      labels:
        name: orchestrator-api
    spec:
      serviceAccountName: orchestrator
      automountServiceAccountToken: true
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        - name: orchestrator-api
          image: ghcr.io/5g-era/orchestrator-api:v1.0.1
          imagePullPolicy: Always
          resources: {}
          env:
            - name: REDIS_INTERFACE_API_SERVICE_HOST
              value: redis-interface-api
            - name: REDIS_INTERFACE_API_SERVICE_PORT
              value: "80"
            - name: Middleware__Organization
              value: 5G-ERA-DEV
            - name: Middleware__InstanceName
              value: MiddlewareEdgeDemo
            - name: Middleware__InstanceType
              value: Edge
            - name: Middleware__Address
              value: http://192.168.50.55:31010
            - name: CENTRAL_API_HOSTNAME
              value: central-api.middleware-central.svc.cluster.local
            - name: CustomLogger__LoggerName
              value: Loki
            - name: CustomLogger__Url
              value: http://loki.loki.svc.cluster.local:3100
            - name: CustomLogger__User
              value: lokiuser
            - name: CustomLogger__Password
              value: lokipassword
            - name: RabbitMQ__Address
              value: rabbitmq.rabbitmq.svc.cluster.local
            - name: RabbitMQ__User
              value: rabbitmquser
            - name: RabbitMQ__Pass
              value: rabbitmqpassword
            - name: Redis__ClusterHostname
              value: redis-master.redis.svc.cluster.local
            - name: Redis__Password
              value: redispassword
            - name: InfluxDB__Address
              value: http://influxdb.influxdb.svc.cluster.local:8086
            - name: InfluxDB__ApiKey
              value: iFPLlUTbrcxlvIgejg0V_8NN-v4RY6BXvXMPE1E8A0y1ivUOfK1bMRbjcwKh06PyXqEbqe7D2G6P23Q35ZcIjQ==