apiVersion: v1
kind: Service
metadata:
  name: hal-5g-era-solvesimulator 
spec:
  type: NodePort
  selector:
    name: hal-5g-era-solvesimulator  
  ports:
    - port: 80
      targetPort: 80
      name: http
    - port: 7176
      targetPort: 7176
      name: grpc