kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: orchestrator-role-binding
  namespace: middleware
subjects:
  - kind: User
    name: middleware-user
  - kind: ServiceAccount
    name: orchestrator
    namespace: middleware
roleRef:
  kind: Role
  name: orchestrator-role
  apiGroup: rbac.authorization.k8s.io
