apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: orchestrator-role
  namespace: middleware
rules:
  - apiGroups: ["", "apps", "batch"]
    resources:
      [
        "services",
        "nodes",
        "namespaces",
        "pods",
        "deployments",
        "daemonsets",
        "statefulsets",
        "replicasets",
        "jobs",
        "pods/log",
        "pods/exec",
      ]
    verbs: ["get", "list", "watch", "create", "delete"]
