apiVersion: apps/v1
kind: Deployment
metadata:
  name: central-api
spec:
  selector:
    matchLabels:
      app: central-api
  template:
    metadata:
      labels:
        app: central-api
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        - name: central-api
          image: ghcr.io/5g-era/central-api:v1.0.0
          imagePullPolicy: Always
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-key
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-key
                  key: AWS_SECRET_ACCESS_KEY
          resources: {}
