apiVersion: v1
kind: Service
metadata:
  name: central-api
spec:
  type: NodePort  
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31003
      name: http
  selector:
    app: central-api
